<script lang="ts">
	import PageHeader from '$lib/components/app/layout/PageHeader.svelte';
	import Toolbar from '$lib/components/app/data/Toolbar.svelte';
	import FilterBar from '$lib/components/app/data/FilterBar.svelte';
	import SearchBar from '$lib/components/app/data/SearchBar.svelte';
	import Button from '$lib/components/app/common/Button.svelte';
	import ContentGrid from '$lib/components/app/layout/ContentGrid.svelte';
	import ChartCard from '$lib/components/app/cards/ChartCard.svelte';
	import { IconPlus } from '@tabler/icons-svelte';

	let search = $state('');
	let filters = $state([
		{
			id: 'type',
			label: 'Chart Type',
			value: 'all',
			options: [
				{ label: 'All Types', value: 'all' },
				{ label: 'Bar', value: 'bar' },
				{ label: 'Line', value: 'line' },
				{ label: 'Scatter', value: 'scatter' }
			]
		}
	]);

	// Mock data for visualizations since it's not in mock/index.ts yet
	const mockCharts: Array<{
		title: string;
		type: 'bar' | 'line' | 'scatter' | 'heatmap' | 'table';
		datasetName: string;
		agentName: string;
		createdAt: string;
	}> = [
		{
			title: 'Q2 Patient Admission Trends',
			type: 'bar',
			datasetName: 'patient_records_q2.csv',
			agentName: 'Clinical Data Analyzer',
			createdAt: '2 hours ago'
		},
		{
			title: 'Lab Results Anomaly Detection',
			type: 'scatter',
			datasetName: 'lab_results_history.json',
			agentName: 'Medical Knowledge Assistant',
			createdAt: 'Yesterday'
		},
		{
			title: 'ER Wait Times Forecast',
			type: 'line',
			datasetName: 'er_logs_2026.csv',
			agentName: 'Predictive Modeler',
			createdAt: '2 days ago'
		},
		{
			title: 'Department Resource Allocation',
			type: 'heatmap',
			datasetName: 'staffing_matrix.xlsx',
			agentName: 'Operations Analyzer',
			createdAt: '1 week ago'
		}
	];

	let charts = $derived.by(() => {
		let filtered = [...mockCharts];
		if (search) {
			filtered = filtered.filter((c) => c.title.toLowerCase().includes(search.toLowerCase()));
		}
		if (filters[0].value !== 'all') {
			filtered = filtered.filter((c) => c.type === filters[0].value);
		}
		return filtered;
	});
</script>

<svelte:head>
	<title>Visualizations | CHU Analytics</title>
</svelte:head>

<div class="p-8 max-w-7xl mx-auto h-full flex flex-col">
	<PageHeader
		title="Visualizations"
		subtitle="Explore interactive charts, graphs, and data visualizations generated by AI."
	>
		<Button variant="primary" icon={IconPlus}>Create Dashboard</Button>
	</PageHeader>

	<Toolbar>
		<SearchBar bind:value={search} placeholder="Search visualizations..." class="w-64" />
		<div class="w-px h-6 bg-border mx-2"></div>
		<FilterBar bind:filters />
	</Toolbar>

	<div class="flex-1 mt-6">
		<ContentGrid columns={3} gap="lg">
			{#each charts as chart}
				<ChartCard
					title={chart.title}
					type={chart.type}
					datasetName={chart.datasetName}
					agentName={chart.agentName}
					createdAt={chart.createdAt}
				/>
			{/each}
		</ContentGrid>
	</div>
</div>
