"""intial_migration

Revision ID: 7d178e5e5c4a
Revises: 
Create Date: 2026-07-30 15:32:27.299728

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d178e5e5c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original filename as uploaded by the user.'),
    sa.Column('storage_filename', sa.String(length=255), nullable=False, comment='Unique filename on disk (to avoid collisions).'),
    sa.Column('filepath', sa.String(length=1024), nullable=False, comment='Absolute path to the file on disk.'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes.'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='MIME type (e.g. text/csv, application/json).'),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'ERROR', name='dataset_status'), nullable=False, comment='Current processing status.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed.'),
    sa.Column('rows', sa.Integer(), nullable=True, comment='Number of rows (populated after processing).'),
    sa.Column('columns', sa.Integer(), nullable=True, comment='Number of columns (populated after processing).'),
    sa.Column('columns_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Column metadata: name, dtype, null count, unique count.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True, comment='Optional linked dataset for this conversation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename on disk.'),
    sa.Column('filepath', sa.String(length=512), nullable=False, comment='Absolute path to the file on disk.'),
    sa.Column('mime_type', sa.String(length=128), nullable=False, comment='MIME type (e.g. image/png).'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_conversation_id'), 'artifacts', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment="'user' or 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('tool_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_evidences_conversation_id'), 'tool_evidences', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_evidences_message_id'), 'tool_evidences', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_evidences_message_id'), table_name='tool_evidences')
    op.drop_index(op.f('ix_tool_evidences_conversation_id'), table_name='tool_evidences')
    op.drop_table('tool_evidences')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_artifacts_conversation_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('conversations')
    op.drop_table('datasets')
    # ### end Alembic commands ###
